# Generated by Django 2.1.7 on 2019-03-12 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(default=datetime.date(2019, 3, 12)),
        ),
    ]
